# Generated by Django 4.1.2 on 2022-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelf', '0002_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
