# Generated by Django 4.1.2 on 2022-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelf', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
